#!/bin/bash
set -e
uv run echo "Linting src tests"
. ./activate
echo Running ruff src
ruff check --fix src
echo Running ruff tests
ruff check --fix tests
echo Running black src tests
black src tests
echo Running isort src tests
isort --profile black src tests
echo Running flake8 src tests
flake8 src tests
echo Running mypy src
mypy src
mypy tests
echo Linting complete!
exit 0
